# Generated by Django 4.2.3 on 2023-09-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoIoT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serialNumber', models.CharField(max_length=255)),
                ('dados', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
