# Generated by Django 4.2.3 on 2023-09-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivoiot',
            name='dados',
            field=models.CharField(max_length=255),
        ),
    ]
